# Basic application configuration
working_dir: "."
app_prompt:
  base_dir: "prompts"
app_schema:
  base_dir: "schema"
logger:
  level: "info"
  format: "text"
output:
  format: "markdown"
  includeHeaders: true
