# Production environment configuration
working_dir: "."
app_prompt:
  base_dir: "prompts/prod"
app_schema:
  base_dir: "../lib/breakdown/schema/prod"
  validation_enabled: true
  strict_mode: true
logger:
  level: "error"
  format: "json"
  output: "stderr"
  includeStackTrace: false
performance:
  maxFileSize: "10MB"
  timeout: 30000
  concurrency: 8
security:
  sanitizeInput: true
  auditLog: true
features:
  experimentalFeatures: false
  debugMode: false
