app_prompt:
  base_dir: "test-app-prompts"
app_schema:
  base_dir: "test-app-schema"
params:
  two:
    demonstrativeType:
      pattern: "^(app-only)$"
logger:
  level: "app-level"
  format: "app-format"
EOF < /dev/null