# User configuration for breakdown
working_dir: "."
app_prompt:
  base_dir: "prompts/user"
app_schema:
  base_dir: "schema/user"

# Workspace configuration
workspace:
  working_dir: ".agent/breakdown"
  temp_dir: ".agent/breakdown/temp"

# カスタムパラメータ設定
params:
  two:
    demonstrativeType:
      pattern: "^(to|summary|defect|find)$"
    layerType:
      pattern: "^(project|issue|task|bugs)$"

# Find bugs カスタム設定
features:
  customConfig: true
  findBugs: true

# Find bugs詳細設定
customConfig:
  enabled: true
  find:
    twoParams:
      - "bugs"
  findBugs:
    enabled: true
    sensitivity: "medium"
    patterns:
      - "TODO"
      - "FIXME" 
      - "HACK"
      - "BUG"
      - "XXX"
      - "DEPRECATED"
      - "console.log"
      - "print("
    includeExtensions:
      - ".ts"
      - ".js"
      - ".py"
      - ".go"
      - ".java"
      - ".cpp"
      - ".c"
    excludeDirectories:
      - "node_modules"
      - ".git"
      - "dist"
      - "build"
      - "target"
      - ".deno"
    maxResults: 100
    detailedReports: true

# Logger configuration
logger:
  level: "info"
  format: "json"
