# Application Configuration
# Base configuration for breakdown CLI

# Application metadata
app:
  name: breakdown
  version: 1.0.0
  description: Breakdown CLI tool

# Default configuration
defaults:
  logLevel: info
  outputFormat: text

# Base configuration that can be overridden by user configs
config:
  enabled: true
