# Default user configuration
# User-specific patterns and settings

params:
  two:
    directiveType:
      pattern: "^(to|summary|defect|fix|refactor|design|test)$"
      errorMessage: "Invalid directive type"
    layerType:
      pattern: "^(project|issue|task|feature|module|component)$"
      errorMessage: "Invalid layer type"

# Test data for validation
testData:
  validDirectives:
    - "to"
    - "summary"
    - "defect"
  validLayers:
    - "project"
    - "issue"
    - "task"
  invalidDirectives:
    - "invalid_directive"
    - "123"
  invalidLayers:
    - "invalid_layer"
    - "456"
