# Default application configuration
app_prompt:
  base_dir: ".agent/breakdown/prompts"

app_schema:
  base_dir: ".agent/breakdown/schema"

output:
  base_dir: "output"

features:
  extendedThinking: false
  debugMode: false
  strictValidation: true
  autoSchema: true

limits:
  maxFileSize: 10485760 # 10MB
  maxPromptLength: 50000
  maxVariables: 100

environment:
  logLevel: "info"
  colorOutput: true
  timezone: "UTC"
  locale: "en-US"

# Pattern definitions
directive_patterns: "to|summary|defect|find"
layer_patterns: "project|issue|task|bugs"
