# Development Application Configuration for Breakdown
# This file contains development environment settings with proper PromptDir configuration

# Application settings
app:
  name: "Breakdown"
  version: "1.0.0"
  description: "Development breakdown application for team collaboration"

# Working directory settings
working_dir: ".agent/breakdown"

# Prompt configuration
app_prompt:
  base_dir: "prompts"

# Schema configuration
app_schema:
  base_dir: "schema"

# Custom configuration for development features
customConfig:
  enabled: true

  # Find bugs configuration for development
  findBugs:
    enabled: true
    sensitivity: "high"
    patterns:
      - "TODO"
      - "FIXME"
      - "HACK"
      - "BUG"
      - "XXX"
      - "DEPRECATED"
      - "DEBUG"
      - "TEMP"
    includeExtensions:
      - ".ts"
      - ".js"
      - ".tsx"
      - ".jsx"
      - ".md"
      - ".json"
      - ".yml"
    excludeDirectories:
      - "node_modules"
      - ".git"
      - "dist"
      - "build"
      - "coverage"
      - ".deno"
      - "tmp"
    maxResults: 100
    detailedReports: true

  # Support for two-parameter commands
  find:
    twoParams:
      - "bugs"

# BreakdownParams configuration for development
breakdownParams:
  version: "1.0.0"
  customConfig:
    params:
      two:
        demonstrativeType:
          pattern: "^(to|find|summary|defect)$"
          errorMessage: "Demonstrative type must be 'to', 'find', 'summary', or 'defect'"
        layerType:
          pattern: "^(project|issue|task|system|bugs|layer)$"
          errorMessage: "Layer type must be valid layer type"
    validation:
      zero:
        allowedOptions: ["help", "version", "init"]
        valueOptions: ["config", "c"]
      one:
        allowedOptions: ["help", "extended", "custom-validation"]
        valueOptions: ["config", "c", "error-format", "destination", "from", "output", "prompt-dir"]
      two:
        allowedOptions: ["help", "extended", "custom-validation"]
        valueOptions: ["config", "c", "error-format", "destination", "from", "output", "prompt-dir"]
    options:
      values:
        config:
          shortForm: "c"
          description: "Configuration file path"
        prompt-dir:
          description: "Custom prompt directory path"
        error-format:
          description: "Error output format"
          allowedValues: ["simple", "detailed", "json"]
        extended:
          description: "Enable extended processing mode"
        custom-validation:
          description: "Enable custom validation mode"

# Development logger configuration
logger:
  level: "debug"
  fileLogging: true
  maxFileSize: 10
  maxBackups: 5

# Development performance settings
performance:
  monitoring: true
  memoryLimit: 512
  timeout: 180
  profiling: true

# Development output settings
output:
  format: "json"
  prettyPrint: true
  includeTimestamps: true
  directory: "./dev-output"

# Development security settings
security:
  enabled: true
  validateInput: true
  sanitizeOutput: true
  maxInputSize: 1024

# Development feature flags
features:
  experimental: true
  beta: true
  custom:
    asyncProcessing: true
    enhancedReporting: true
    smartCaching: true
    teamCollaboration: true
    devMode: true
