# Flexible test configuration for broader pattern testing
#
# This file provides more flexible patterns for testing edge cases

params:
  two:
    directiveType:
      pattern: "^(to|summary|defect|to#\\d+|summary#\\d+)$"
      errorMessage: "Invalid directive type for flexible profile"
    layerType:
      pattern: "^(project|issue|task|project#\\d+|issue#\\d+)$"
      errorMessage: "Invalid layer type for flexible profile"

# Flexible validation settings
validation:
  enabled: true
  strictMode: false
  allowSpecialChars: true

# Extended testing values
directiveValues:
  - "to"
  - "summary"
  - "defect"
  - "to#1"
  - "summary#1"

layerTypeValues:
  - "project"
  - "issue"
  - "task"
  - "project#1"
  - "issue#1"

# Test data for integration tests
testData:
  validDirectives:
    - "to"
    - "summary"
    - "defect"
    - "to#1"
    - "summary#1"
  validLayers:
    - "project"
    - "issue"
    - "task"
    - "project#1"
    - "issue#1"
  invalidDirectives:
    - "invalid"
    - "unknown"
  invalidLayers:
    - "invalid"
    - "unknown"

# Resource paths for test fixtures
paths:
  resourceDir: "./tests/fixtures"
  templateDir: "./tests/fixtures/prompts"
