# Production User Configuration for Breakdown
# This file contains user-specific production settings for bug detection and analysis

# User settings
app:
  name: "Breakdown"
  version: "1.0.0"
  description: "Production breakdown application for bug detection and document processing"

# Working directory settings
working_dir: ".agent/breakdown"

# Prompt configuration
app_prompt:
  base_dir: "lib/breakdown/prompts"

# Schema configuration
app_schema:
  base_dir: "lib/breakdown/schema"

# Custom configuration for advanced features
customConfig:
  enabled: true

  # Find bugs configuration
  findBugs:
    enabled: true
    sensitivity: "medium"
    patterns:
      - "TODO"
      - "FIXME"
      - "HACK"
      - "BUG"
      - "XXX"
      - "DEPRECATED"
    includeExtensions:
      - ".ts"
      - ".js"
      - ".tsx"
      - ".jsx"
      - ".md"
    excludeDirectories:
      - "node_modules"
      - ".git"
      - "dist"
      - "build"
      - "coverage"
      - ".obsidian"
    maxResults: 100
    detailedReports: true

  # Support for two-parameter commands
  find:
    twoParams:
      - "bugs"

# BreakdownParams configuration
breakdownParams:
  version: "latest"
  customParams:
    enabled: true
    allowDynamicParams: true
    paramValidation: true
    maxParamLength: 256
  customConfig:
    params:
      two:
        demonstrativeType:
          pattern: "^(to|find)$"
          errorMessage: "Demonstrative type must be 'to' or 'find'"
        layerType:
          pattern: "^(project|system|bugs|layer)$"
          errorMessage: "Layer type must be 'project', 'system', 'bugs', or 'layer'"
    validation:
      zero:
        allowedOptions: ["help", "version", "init"]
        valueOptions: ["config", "c"]
        allowCustomVariables: false
      one:
        allowedOptions: ["help", "extended", "custom-validation"]
        valueOptions: ["config", "c", "error-format", "destination", "from", "output", "prompt-dir"]
        allowCustomVariables: true
      two:
        allowedOptions: ["help", "extended", "custom-validation"]
        valueOptions: ["config", "c", "error-format", "destination", "from", "output", "prompt-dir"]
        allowCustomVariables: true
    options:
      values:
        config:
          shortForm: "c"
          description: "Configuration file path"
        prompt-dir:
          description: "Custom prompt directory path"
        error-format:
          description: "Error output format"
          allowedValues: ["simple", "detailed", "json"]
        extended:
          description: "Enable extended processing mode"
      customVariables:
        pattern: "^--uv-[a-zA-Z-]+$"
        description: "Custom user variables with --uv- prefix"
      flags:
        help:
          description: "Show help information"
        extended:
          description: "Enable extended processing mode"
        custom-validation:
          description: "Enable custom validation mode"
    errorHandling:
      enabled: true
      logLevel: "error"
      retryAttempts: 3
      gracefulDegradation: true
      unknownOption: "error"
      duplicateOption: "warn"
      emptyValue: "error"

# Production logger configuration
logger:
  level: "info"
  fileLogging: true
  maxFileSize: 10
  maxBackups: 5

# Production performance settings
performance:
  monitoring: true
  memoryLimit: 512
  timeout: 300
  profiling: false

# Production output settings
output:
  format: "json"
  prettyPrint: true
  includeTimestamps: true
  directory: "./output"

# Production security settings
security:
  enabled: true
  validateInput: true
  sanitizeOutput: true
  maxInputSize: 1024

# Production feature flags
features:
  experimental: false
  beta: false
  custom:
    asyncProcessing: true
    enhancedReporting: true
    smartCaching: true
