# Breakdown application configuration for staging environment
# This file works with staging-user.yml for custom parameter support

# Application metadata
app:
  name: breakdown-staging
  version: 1.0.0
  description: Breakdown CLI tool - staging environment

# Default configuration
defaults:
  logLevel: info
  outputFormat: text

# Base configuration
config:
  enabled: true

# Working directory - required at top level by BreakdownConfig
working_dir: ".agent/breakdown"

# Prompt and schema configuration (same as default)
app_prompt:
  base_dir: "lib/breakdown/prompts"
app_schema:
  base_dir: "lib/breakdown/schema"

# Define custom parameters that work with staging-user.yml
params:
  two:
    demonstrativeType:
      pattern: "^(to|from|via|find)$"
    layerType:
      pattern: "^(project|issue|task|epic|system)$"

# Workspace configuration
workspace:
  temp_dir: ".agent/breakdown/temp"
