# Breakdown user configuration for staging environment
# This configuration allows "find" and "system" as custom parameters

# Custom parameters configuration - direct format
params:
  two:
    demonstrativeType:
      pattern: "^(to|from|via|find)$"
      errorMessage: "Invalid demonstrative type. Must be one of: to, from, via, find"
    layerType:
      pattern: "^(project|issue|task|epic|system)$"
      errorMessage: "Invalid layer type. Must be one of: project, issue, task, epic, system"

validation:
  zero:
    allowedOptions: ["help", "version"]
    allowedValueOptions: []
  one:
    allowedOptions: ["verbose"]
    allowedValueOptions: ["config"]
  two:
    allowedOptions: ["verbose", "experimental"]
    allowedValueOptions: ["from", "destination", "input", "config"]

options:
  verbose:
    type: "boolean"
    default: false
  config:
    type: "string"
    default: null

errorHandling:
  unknownOption: "error"
  duplicateOption: "error"
  emptyValue: "error"

# Also keep breakdownParams for compatibility
breakdownParams:
  customConfig:
    params:
      two:
        demonstrativeType:
          pattern: "^(to|from|via|find)$"
          errorMessage: "Invalid demonstrative type. Must be one of: to, from, via, find"
        layerType:
          pattern: "^(project|issue|task|epic|system)$"
          errorMessage: "Invalid layer type. Must be one of: project, issue, task, epic, system"

    validation:
      zero:
        allowedOptions: ["help", "version"]
        allowedValueOptions: []
      one:
        allowedOptions: ["verbose"]
        allowedValueOptions: ["config"]
      two:
        allowedOptions: ["verbose", "experimental"]
        allowedValueOptions: ["from", "destination", "input", "config"]

    options:
      verbose:
        type: "boolean"
        default: false
      config:
        type: "string"
        default: null

    errorHandling:
      unknownOption: "error"
      duplicateOption: "error"
      emptyValue: "error"
