# Test Application Configuration for Breakdown
# This file contains test environment settings with proper PromptDir configuration

# Application settings
app:
  name: "Breakdown"
  version: "1.0.0"
  description: "Test breakdown application for development and testing"

# Working directory settings
working_dir: ".agent/breakdown/test"

# Prompt configuration with explicit directory settings
app_prompt:
  base_dir: "prompts"
  prompt_dir: "prompts/test"

# Schema configuration
app_schema:
  base_dir: "schema"
  schema_dir: "schema/test"

# Custom configuration for test features
customConfig:
  enabled: true

  # Find bugs configuration for testing
  findBugs:
    enabled: true
    sensitivity: "high"
    patterns:
      - "TODO"
      - "FIXME"
      - "HACK"
      - "BUG"
      - "XXX"
      - "DEPRECATED"
      - "TEST"
      - "DEBUG"
    includeExtensions:
      - ".ts"
      - ".js"
      - ".tsx"
      - ".jsx"
      - ".md"
      - ".json"
    excludeDirectories:
      - "node_modules"
      - ".git"
      - "dist"
      - "build"
      - "coverage"
    maxResults: 50
    detailedReports: true

  # Support for two-parameter commands
  find:
    twoParams:
      - "bugs"

# BreakdownParams configuration for test environment
breakdownParams:
  version: "1.0.0"
  customConfig:
    params:
      two:
        demonstrativeType:
          pattern: "^(to|find|summary|defect)$"
          errorMessage: "Demonstrative type must be 'to', 'find', 'summary', or 'defect'"
        layerType:
          pattern: "^(project|issue|task|system|bugs|layer)$"
          errorMessage: "Layer type must be valid layer type"
    validation:
      zero:
        allowedOptions: ["help", "version", "init"]
        valueOptions: ["config", "c"]
      one:
        allowedOptions: ["help", "extended", "custom-validation"]
        valueOptions: ["config", "c", "error-format", "destination", "from", "output", "prompt-dir"]
      two:
        allowedOptions: ["help", "extended", "custom-validation"]
        valueOptions: ["config", "c", "error-format", "destination", "from", "output", "prompt-dir"]
    options:
      values:
        config:
          shortForm: "c"
          description: "Configuration file path"
        prompt-dir:
          description: "Custom prompt directory path"
        error-format:
          description: "Error output format"
          allowedValues: ["simple", "detailed", "json"]
        extended:
          description: "Enable extended processing mode"
        custom-validation:
          description: "Enable custom validation mode"

# Test logger configuration
logger:
  level: "debug"
  fileLogging: true
  maxFileSize: 5
  maxBackups: 3

# Test performance settings
performance:
  monitoring: true
  memoryLimit: 256
  timeout: 120
  profiling: true

# Test output settings
output:
  format: "json"
  prettyPrint: true
  includeTimestamps: true
  directory: "./test-output"

# Test security settings
security:
  enabled: true
  validateInput: true
  sanitizeOutput: true
  maxInputSize: 512

# Test feature flags
features:
  experimental: true
  beta: true
  custom:
    asyncProcessing: true
    enhancedReporting: true
    smartCaching: false
    testMode: true
