/**
 * Generated Schema Definitions
 * 
 * This file is auto-generated from the assets/schemas directory.
 * Do not edit this file directly.
 */

export const SCHEMAS = {
  defect: {
  },
  to: {
    project: `{
  "\$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "gitHubProjectNumber",
    "projectName",
    "summary",
    "issues"
  ],
  "properties": {
    "gitHubProjectNumber": {
      "type": "integer",
      "description": "GitHub project number"
    },
    "projectName": {
      "type": "string",
      "description": "Name of the project"
    },
    "summary": {
      "type": "string",
      "description": "Project summary"
    },
    "issues": {
      "type": "array",
      "items": {
        "\$ref": "issue.schema.json"
      }
    }
  }
}`,
    issue: `{
  "\$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "projectId": {
      "type": "string",
      "description": "プロジェクトの一意のID, GitHubのProjectIDが、入力ファイルや入力内容にあればセットします。"
    },
    "projectName": {
      "type": "string",
      "description": "プロジェクトの名称"
    },
    "projectDescription": {
      "type": "string",
      "description": "プロジェクトの説明"
    },
    "status": {
      "type": "string",
      "enum": [
        "未着手",
        "進行中",
        "完了"
      ],
      "description": "プロジェクトの状態"
    },
    "priority": {
      "type": "string",
      "enum": [
        "高",
        "中",
        "低"
      ],
      "description": "プロジェクトの優先度"
    },
    "projectGoal": {
      "type": "string",
      "description": "プロジェクトの最終的なゴールや達成すべき目標"
    },
    "projectType": {
      "type": "string",
      "enum": [
        "機能追加",
        "バグ修正",
        "エラー対応",
        "リファクタリング",
        "パフォーマンス改善",
        "セキュリティ対策",
        "テスト",
        "ドキュメンテーション",
        "デプロイメント",
        "インフラストラクチャ改善",
        "ユーザーインターフェイス改善",
        "技術的負債の解消",
        "ソフトウェア更新",
        "プラットフォーム移行",
        "API設計・改善",
        "システム統合",
        "障害対応",
        "バックアップと復元",
        "自動化",
        "顧客要望対応",
        "バージョン管理",
        "A/Bテスト",
        "ローカリゼーション・国際化"
      ],
      "description": "プロジェクトの種類"
    },
    "previousProject": {
      "type": "string",
      "description": "前のプロジェクトID（任意項目）"
    },
    "nextProject": {
      "type": "string",
      "description": "次のプロジェクトID（任意項目）"
    },
    "issues": {
      "type": "array",
      "items": {
        "\$ref": "issue.schema.json"
      },
      "description": "プロジェクトに関連する複数の課題"
    }
  },
  "required": [
    "projectId",
    "projectName",
    "status",
    "priority",
    "projectGoal",
    "projectType",
    "issues"
  ]
}`,
    task: `{
  "\$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "taskId",
    "description",
    "taskType",
    "taskState",
    "taskProperties",
    "steps"
  ],
  "properties": {
    "taskId": {
      "type": "integer",
      "description": "Unique identifier for the task"
    },
    "description": {
      "type": "string",
      "description": "Task description"
    },
    "taskType": {
      "type": "string",
      "description": "Type of the task"
    },
    "taskState": {
      "type": "string",
      "enum": [
        "ToDo",
        "Doing",
        "Done",
        "Error",
        "Crash"
      ],
      "description": "Current state of the task"
    },
    "taskProperties": {
      "type": "array",
      "items": {
        "\$ref": "task_property.schema.json"
      }
    },
    "steps": {
      "type": "array",
      "items": {
        "\$ref": "step.schema.json"
      }
    }
  }
}`,
  },
};
