// このファイルは自動生成されています。直接編集しないでください。
/**
 * 元: lib/breakdown/schema 配下のMarkdownテンプレート
 */
export const schema = {
  "to/project/base.schema.md":
    '# Project Schema\n\n\\`\\`\\`json\n{\n  "\\$schema": "http://json-schema.org/draft-07/schema#",\n  "type": "object",\n  "properties": {\n    "project": {\n      "type": "object",\n      "properties": {\n        "name": { "type": "string" },\n        "description": { "type": "string" },\n        "objectives": {\n          "type": "array",\n          "items": { "type": "string" }\n        },\n        "deliverables": {\n          "type": "array",\n          "items": { "type": "string" }\n        },\n        "requirements": {\n          "type": "array",\n          "items": { "type": "string" }\n        },\n        "timeline": {\n          "type": "object",\n          "properties": {\n            "start": { "type": "string" },\n            "end": { "type": "string" }\n          }\n        }\n      },\n      "required": ["name", "description", "objectives", "deliverables", "requirements"]\n    }\n  }\n}\n\\`\\`\\` ',
  "to/issue/base.schema.md":
    '# Issue Schema\n\n\\`\\`\\`json\n{\n  "\\$schema": "http://json-schema.org/draft-07/schema#",\n  "type": "object",\n  "properties": {\n    "issues": {\n      "type": "array",\n      "items": {\n        "type": "object",\n        "properties": {\n          "title": { "type": "string" },\n          "description": { "type": "string" },\n          "acceptance_criteria": {\n            "type": "array",\n            "items": { "type": "string" }\n          },\n          "dependencies": {\n            "type": "array",\n            "items": { "type": "string" }\n          },\n          "priority": {\n            "type": "string",\n            "enum": ["high", "medium", "low"]\n          },\n          "effort": {\n            "type": "string",\n            "enum": ["small", "medium", "large"]\n          }\n        },\n        "required": ["title", "description", "acceptance_criteria", "priority", "effort"]\n      }\n    }\n  }\n}\n\\`\\`\\` ',
  "to/task/base.schema.md":
    '# Task Schema\n\n\\`\\`\\`json\n{\n  "\\$schema": "http://json-schema.org/draft-07/schema#",\n  "type": "object",\n  "properties": {\n    "tasks": {\n      "type": "array",\n      "items": {\n        "type": "object",\n        "properties": {\n          "title": { "type": "string" },\n          "description": { "type": "string" },\n          "steps": {\n            "type": "array",\n            "items": { "type": "string" }\n          },\n          "dependencies": {\n            "type": "array",\n            "items": { "type": "string" }\n          },\n          "priority": {\n            "type": "string",\n            "enum": ["high", "medium", "low"]\n          },\n          "estimate": {\n            "type": "string",\n            "pattern": "^[0-9]+h\\$"\n          },\n          "technical_requirements": {\n            "type": "array",\n            "items": { "type": "string" }\n          }\n        },\n        "required": ["title", "description", "steps", "priority", "estimate"]\n      }\n    }\n  }\n}\n\\`\\`\\` ',
} as const;
