name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.5.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate version format
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in format x.y.z (e.g., 1.5.0)"
            exit 1
          fi

      - name: Check if version exists
        run: |
          if git rev-parse "v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "Error: Tag v${{ github.event.inputs.version }} already exists"
            exit 1
          fi

      - name: Create and push tag
        run: |
          TAG_NAME="v${{ github.event.inputs.version }}"
          echo "Creating release tag: $TAG_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "✅ Tag $TAG_NAME created and pushed successfully"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "Release v${{ github.event.inputs.version }}"
          body: |
            Release v${{ github.event.inputs.version }}
            
            ## Changes
            - Please update this release description with the actual changes
            
            ## Installation
            ```bash
            deno add @tettuan/breakdown@${{ github.event.inputs.version }}
            ```
          draft: false
          prerelease: false

      - name: Output success message
        run: |
          echo "🎉 Release v${{ github.event.inputs.version }} created successfully!"
          echo "📦 This will trigger the publish workflow to JSR"
          echo "🔗 Release URL: https://github.com/${{ github.repository }}/releases/tag/v${{ github.event.inputs.version }}"
