name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication with deno publish
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      # Check if tag is on main
      - name: Check if tag is on main
        id: check-tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
          else
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          fi
          
          TAG_COMMIT=$(git rev-parse $TAG_NAME)
          if git rev-list main | grep -q "^$TAG_COMMIT$"; then
            echo "✅ Tag $TAG_NAME is on main branch"
          else
            echo "❌ Tag $TAG_NAME is not on main branch"
            exit 1
          fi
      # Extract version from tag
      - name: Get tag version
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
          else
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          fi
          TAG_VERSION="${TAG_NAME#v}"
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      # Fetch latest JSR version
      - name: Get latest JSR version
        id: get_jsr
        run: |
          LATEST_JSR_VERSION=$(curl -s https://jsr.io/@tettuan/breakdown/meta.json | jq -r '.versions | keys | .[-1]')
          echo "LATEST_JSR_VERSION=$LATEST_JSR_VERSION" >> $GITHUB_ENV
      # Compare versions and skip if tag is not newer
      - name: Check if tag version is newer than JSR
        id: check_version
        run: |
          if [ -z "$LATEST_JSR_VERSION" ]; then
            echo "No JSR version found, proceeding with publish.";
            exit 0;
          fi
          if [ "$(printf '%s\n%s\n' "$LATEST_JSR_VERSION" "$TAG_VERSION" | sort -V | tail -n1)" != "$TAG_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) is not newer than JSR latest ($LATEST_JSR_VERSION). Skipping publish.";
            exit 78;
          fi
      # Run CI tasks (tests, format check, and lint)
      - name: Run CI
        run: deno task ci
      # Publish to JSR using OIDC (no token required)
      - name: Publish to JSR (OIDC)
        run: deno publish
        # OIDC is used automatically when id-token: write is set
