name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Install Deno
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # Run tests before publishing
      - name: Run tests
        run: deno test --allow-env --allow-write --allow-read --allow-run

      # Run format check
      - name: Check formatting
        run: deno fmt --check

      # Run lint check
      - name: Run linter
        run: deno lint

      # Publish to JSR
      - name: Publish to JSR
        run: npx jsr publish
