name: Version Consistency Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Get latest tag version
        id: get_tag
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Check deno.json version matches latest tag
        run: |
          deno run --allow-read --unstable <<'EOF'
          const denoJson = JSON.parse(await Deno.readTextFile('deno.json'));
          const denoVersion = denoJson.version;
          const tagVersion = Deno.env.get('TAG_VERSION');
          if (denoVersion !== tagVersion) {
            console.error(`Version mismatch!\n deno.json: ${denoVersion}\n git tag: ${tagVersion}`);
            Deno.exit(1);
          } else {
            console.log(`deno.json and git tag version match: ${denoVersion}`);
          }
          EOF
