name: Version Consistency Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Check version consistency
        run: |
          deno run --allow-read --unstable <<'EOF'
          // Read deno.json version
          const denoJson = JSON.parse(await Deno.readTextFile('deno.json'));
          const denoVersion = denoJson.version;

          // Read version.ts version
          const versionTs = await Deno.readTextFile('version.ts');
          const match = versionTs.match(/VERSION = "([^"]+)"/);
          if (!match) throw new Error('version.ts: VERSION not found');
          const versionTsVersion = match[1];

          if (denoVersion !== versionTsVersion) {
            console.error(`Version mismatch!\n deno.json: ${denoVersion}\n version.ts: ${versionTsVersion}`);
            Deno.exit(1);
          } else {
            console.log(`All local versions match: ${denoVersion}`);
          }
          EOF
